-- ============================================================================
-- Update Default Admin Password
-- ============================================================================
-- This script updates the default admin user with a proper bcrypt hash
-- Default password: The value from ADMIN_PASSWORD environment variable
-- Run this after the container is built with bcrypt installed
-- ============================================================================

-- Note: The actual password hash will be generated by the application
-- on first startup if ADMIN_PASSWORD environment variable is set.
-- This is handled in server.js startup code.

-- For manual updates, generate a hash using:
-- node -e "import('bcrypt').then(b => b.hash('your_password', 10).then(console.log))"
-- Then run:
-- UPDATE users SET password_hash = '$2b$10$...' WHERE username = 'admin';
